### ISSUE TITLE
no decryption, when two private keys are in Kleopatra

### ISSUE THREAD

**Issue by Genis-Sage** [dejavusecurity/OutlookPrivacyPlugin#28]
I have more than one account in Outlook 2010...
If I only have a (private) key file, for one account, evrything works fine...

But I tried it with two different account (private and work, at the moment to test GPG):
Encryption works, but independently of the choice of direction (private -> work, work -> private), OPP always say, "incorrect Password possibly entered"....

Then I copied the Messages into gpg4usb and everything worked as planned

Perhaps it's only some very special problem, I'll try, what happens, when someone different sends me an mail

**Comment by Meddington** [comment]
I believe this is likely fixed in beta 41.  My guess is different passphrases are used between the keys? Could you please verify if this is still an issue?

**Comment by fidel1** [comment]
Hi Michael, still using win7 x64, outlook 2013 x64, and keys are RSA 2048 bit generated by Kleopatra. Each key has its own password. We removed OPP version beta 38, and installed the latest beta 43, build 5622, dated May 24, 2015. We have now the same error, incorrect passphrase possible entered, if we try to decrypt the message with only one of the keys. If we use both passwords, each at its corresponding key, the message is decrypt correctly. It’s better than what happened in the past, but the idea is that you may decrypt it using only one of the keys. It shows one of the keys, requesting the password, and if you press abort, it must show you the next key, asking for password. And so on, using all keys that were used at encrypting the message. Kleopatra works like that. It’s important because each user knows only their password, and all of the users must be in the position of decrypting the message.

**Comment by Meddington** [comment]
Okay I will adjust. Though I find it very strange that you would have a secret key in your ring that you did not know the password to.  You should never have another users private key.

**Comment by Meddington** [comment]
Fixed and in BETA 44.

**Comment by fidel1** [comment]
Thanks Michael. We removed OPP version beta 43, and installed beta 44, build 5624, dated May 26, 2015. It works very well. Thank you for the effort.
