### ISSUE TITLE
Allow permanently saving decrypted message by default.

### ISSUE THREAD

**Issue by Meddington** [dejavusecurity/OutlookPrivacyPlugin#64]
See issue #57.

By default emails are stored encrypted as they will get synced back to the server.  A feature to allow saving as clear-text has been requested.

**Comment by tx3eh8IUD1** [comment]
(Maybe a feature that only works when using POP3 as opposed to IMAP or Exchange)

**Comment by BuildTheRobots** [comment]
With previous versions it'd do the decrypt and then ask me if I wanted to save changes.
Selecting yes would save the decrypted email back to my IMAP inbox, selecting no would leave it encrypted.

With the latest version[1] selecting "No" to the save prompt _still_ seems to save the unencrypted version back to the IMAP server. 
This is exactly not what I want. Is this expected behaviour and/or is there any way of disabling it, please?

[1] I believe I'm running v1 Beta-40, but I can't actually work out how to check :)

**Comment by Meddington** [comment]
Added a new setting for BETA 47.
